server:
   port: 8080


ribbon:
  eureka:
    enabled: false

user-service:
  ribbon:
    MaxAutoRetries: 0
    listOfServers: 127.0.0.1:8082

todo-service:
  ribbon:
    MaxAutoRetries: 0
    listOfServers: 127.0.0.1:8081

zuul:
  debug:
    request: true
  routes:
    user:
      path: /api/user/**
      serviceId: user-service
      strip-prefix: false
    todos:
      path: /api/todos/**
      serviceId: todo-service
      strip-prefix: false

  sensitive-headers:
logging:
  level:
    org:
      springframework:
         cloud:
           netflix: TRACE
#spring:
#  application:
#    name: zuul-service
#  cloud:
#    consul:
#      host: consul
#      port: 8500
#      discovery:
#        instance-id: ${spring.application.name}:${random.int}
